### ISSUE TITLE
Exception in thread "main" java.io.FileNotFoundException on windows

### ISSUE THREAD

**Issue by saicrazyfire** [tanrax/RSSPAPER#2]
Running this in windows 10 cmd.exe gives FileNotFoundException error. The config.yaml is exactly the same as your example in the readme.

```
C:\Users\saicrazyfire\Documents\Workspace\rsspaper>java -jar rsspaper-1.1.1-standalone.jar
"Reading feeds... Please be patient."
"Reading RSS > https://programadorwebvalencia.com/feed/"
"Reading RSS > https://republicaweb.es/feed/"
"Reading RSS > https://programadorwebvalencia.com/feed/"
"Reading RSS > https://republicaweb.es/feed/"
Exception in thread "main" java.io.FileNotFoundException: \tmp\rsspaper.zip (The system cannot find the path specified)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at clojure.java.io$fn__11522.invokeStatic(io.clj:230)
        at clojure.java.io$fn__11522.invoke(io.clj:230)
        at clojure.java.io$fn__11459$G__11428__11466.invoke(io.clj:69)
        at clojure.java.io$fn__11534.invokeStatic(io.clj:263)
        at clojure.java.io$fn__11534.invoke(io.clj:259)
        at clojure.java.io$fn__11459$G__11428__11466.invoke(io.clj:69)
        at clojure.java.io$output_stream.invokeStatic(io.clj:153)
        at clojure.java.io$output_stream.doInvoke(io.clj:138)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at rsspaper.html$copy_uri_to_file.invokeStatic(html.clj:12)
        at rsspaper.html$copy_uri_to_file.invoke(html.clj:10)
        at rsspaper.html$make_html.invokeStatic(html.clj:34)
        at rsspaper.html$make_html.invoke(html.clj:15)
        at rsspaper.core$_main.invokeStatic(core.clj:9)
        at rsspaper.core$_main.doInvoke(core.clj:6)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at rsspaper.core.main(Unknown Source)
```

A dist and log folder is created with an index.html in dist but nothing else. No CSS/JS, etc

Looking at the JS console shows this:
![image](https://user-images.githubusercontent.com/1043534/128617439-4a970db3-ec76-460a-9155-22806c47090a.png)

**Comment by tanrax** [comment]
The error occurs basically because in Windows there is no temporary folder /tmp/. I never thought that someone would use it outside of a unix or bsd environment.
Thanks for the report, I will investigate.

**Comment by tanrax** [comment]
I have just applied a patch. Please try it.

https://github.com/tanrax/RSSPAPER/releases/tag/v1.1.2

**Comment by tanrax** [comment]
@saicrazyfire Were you able to test it?

**Comment by saicrazyfire** [comment]
@tanrax it worked! Thanks!
